---
title: "Weather Data Import"
format: html
---

# Setup  
```{r}
#| message: false
#| warning: false

#install.packages("sf")
#install.packages("daymetr")
#install.packages("remotes")
#remotes::install_github("ropensci/USAboundaries")
#remotes::install_github("ropensci/USAboundariesData")

library(tidyverse)
library(USAboundaries) # for US state boundaries
library(sf) # for US map
library(daymetr)
```

```{r}
field <- read.csv("../data/raw/training_meta.csv")

field
```

# EDA  
```{r}
summary(field)
```

```{r deleting Germany}
fieldw <- filter(field, longitude < 0) %>%
  select(-previous_crop)
summary(fieldw)
```


```{r unique years}
unique(fieldw$year) %>% length()
```
```{r unique sites}
unique(fieldw$site) %>% length
```

```{r}
states <- us_states() %>% 
  filter( !(state_abbr %in% c("PR", "AK", "HI") ) )

states


ggplot()+
  geom_sf(data = states) +
  geom_point(data = fieldw,
             aes(x = longitude,
                 y = latitude))

```

# Open weather data - all site years


```{r weather data}
daymet_all <- fieldw %>%
  mutate(weather = pmap(list(.y = year,
                        .site = site,
                        .lat = latitude,
                        .lon = longitude),
                    function(.y, .site, .lat, .lon)
                      download_daymet(
                        site = .site,
                        lat = .lat,
                        lon = .lon,
                        start = .y,
                        end = .y,
                        simplify = T,
                        silent = T
                      ) %>%
                    rename(.year = year,
                           .site = site, 
                           .lat = latitude,
                           .lon = longitude
                           )
                    ))

head(daymet_all)
```


```{r unnest}
daymet_all_unnest <- daymet_all %>%
  unnest(weather) %>%
  pivot_wider(names_from = measurement,
              values_from = value
              ) %>%
  janitor::clean_names() %>%
  unnest()


daymet_all_unnest

```


 
```{r save partially cleaned weather data}
write_csv(daymet_all_unnest,
          "../data/weather_partial.csv"
          )
```


# Install degday   
```{r}
options(repos = c(ajlyons = 'https://ajlyons.r-universe.dev',
                  CRAN = 'https://cloud.r-project.org'))
install.packages('degday')

library(degday)
```
```{r import weather as fresh dataset}
weatherpre <- read.csv("../data/weather_partial.csv")

weatherpre
```

```{r double sine GDD code development}
thresh_low = 10
thresh_up = 100

weather <- weatherpre %>%
  mutate(tmin_next = lead(tmin_deg_c, n = 1)) %>%
  mutate(gdd_dbl_sine = dd_dbl_sine(daily_min = tmin_deg_c, 
                                daily_max = tmax_deg_c, 
                                nextday_min = tmin_next,
                                thresh_low = thresh_low, 
                                thresh_up = thresh_up))

weather
```

  





